#  


- name: "Open LDAP Firewall Port"
  become: yes
  firewalld:
    immediate: yes
    permanent: yes
    service: "ldap"
    state: "enabled"
- name: "Copy conf.ldif File"
  become: yes
  copy:
    dest: "/etc/openldap/schema/conf.ldif"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/openldap/conf.ldif"
- name: "Copy base.ldif File"
  become: yes
  copy:
    dest: "/etc/openldap/schema/base.ldif"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/openldap/base.ldif"
- name: "Copy Users .ldif Files"
  become: yes
  copy:
    dest: "/etc/openldap/schema/user-{{ new_ldap_user_name }}.ldif"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/openldap/users/{{ new_ldap_user_name }}.dif"
  loop: "{{ openldap.users }}"
  loop_control:
    loop_var: new_ldap_user_name
- name: "Copy DB_CONFIG File"
  become: yes
  copy:
    dest: "/var/lib/ldap/DB_CONFIG"
    group: "ldap"
    owner: "ldap"
    remote_src: yes
    src: "/usr/share/openldap-servers/DB_CONFIG.example"
- name: "Apply conf.ldif"
  become: yes
  command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/conf.ldif"
- name: "Apply cosine.ldif"
  become: yes
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif"
- name: "Apply nis.ldif"
  become: yes
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif"
- name: "Apply inetorgperson.ldif"
  become: yes
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif"
- name: "Apply base.ldif"
  become: yes
  command: "ldapadd -x -D \"cn={{ openldap.rootdn }},dc={{ openldap.domain }},dc={{ openldap.tld }}\" -f /etc/openldap/schema/base.ldif -w {{ lookup('password', 'credentials/' + inventory_hostname + '/openldap/rootpassword length=12 chars=ascii_letters') }}"
- name: "Apply Users .ldif"
  become: yes
  command: "ldapadd -x -D \"cn={{ openldap.rootdn }},dc={{ openldap.domain }},dc={{ openldap.tld }}\" -f /etc/openldap/schema/user-{{ new_ldap_user_name }}.ldif -w {{ lookup('password', 'credentials/' + inventory_hostname + '/openldap/rootpassword length=12 chars=ascii_letters') }}"
  loop: "{{ openldap.users }}"
  loop_control:
    loop_var: new_ldap_user_name
- name: "Set Users Passwords"
  become: yes
  command: "ldappasswd -s {{ lookup('password', 'credentials/' + inventory_hostname + '/openldap/{{ new_ldap_user_name }}password length=12 chars=ascii_letters') }} -x \"uid={{ new_ldap_user_name }},dc={{ openldap.domain }},dc={{ openldap.tld }}\" -D \"cn={{ openldap.rootdn }},dc={{ openldap.domain }},dc={{ openldap.tld }}\" -f /etc/openldap/schema/user-{{ new_ldap_user_name }}.ldif -w {{ lookup('password', 'credentials/' + inventory_hostname + '/openldap/rootpassword length=12 chars=ascii_letters') }}"
  loop: "{{ openldap.users }}"
  loop_control:
    loop_var: new_ldap_user_name
