- name: "Create Build Folder"
  file:
    path: "./build/{{ inventory_hostname }}/openldap/"
    state: "directory"
- name: "Create Config LDIF"
  template:
    dest: "./build/{{ inventory_hostname }}/openldap/conf.ldif"
    src: "./templates/conf-ldif.j2"
- name: "Create Base LDIF"
  template:
    dest: "./build/{{ inventory_hostname }}/openldap/base.ldif"
    src: "./templates/base-ldif.j2"
