- include_tasks: "install-{{ ansible_facts['os_family'] | lower }}.yml"
- name: "Generate LDAP Root Password"
  become: yes
  command: "slappasswd -h {SSHA} -s {{ lookup('password', 'credentials/' + inventory_hostname + '/openldap/rootpassword length=12 chars=ascii_letters') }}"
  register: LDAP_ROOT_HASH