- name: "Open Syslog Firewall Port"
  become: yes
  firewalld:
    immediate: yes
    permanent: yes
    service: "syslog"
    state: "enabled"
- name: "Copy Config File to /etc"
  become: yes
  copy:
    dest: "/etc/rsyslog.d/server.conf"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/rsyslog.conf"
- name: "Restart Rsyslog"
  become: yes
  service:
    enabled: yes
    name: "rsyslog"
    state: "started"