- name: "Create Build Folder"
  file:
    path: "./build/{{ inventory_hostname }}/"
    state: "directory"
- name: "Create Config"
  template:
    dest: "./build/{{ inventory_hostname }}/rsyslog.conf"
    src: "./config.j2"