- name: "Create Config Staging Folder"
  file:
    state: "directory"
    path: "./staging/{{ inventory_hostname }}/rsyslog/config/"
- name: "Create Config"
  template:
    dest: "./build/{{ inventory_hostname }}/rsyslog.conf"
    src: "./config.j2"