---
- name: DEBUG
  hosts: all
  tasks:
     - debug:
        msg: "{{ hostvars[inventory_hostname] }}"
     - debug:
        msg: "{{ hostvars['localhost'] }}"
     - debug:
        msg: "{{ vars }}"
     - debug:
        msg: "{{ dnsmasq }}"