- name: "Open Tacacs Firewall Port"
  become: yes
  firewalld:
    immediate: yes
    port: "49/tcp"
    permanent: yes
    state: "enabled"
- name: "Copy Config File to /etc"
  become: yes
  copy:
    dest: "/etc/tac_plus.conf"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/tac_plus.conf"
- name: "Restart tac_plus"
  become: yes
  service:
    enabled: yes
    name: "tac_plus"
    state: started