- name: "Open Tacacs Firewall Port"
  become: yes
  firewalld:
    service: tacacs
    permanent: yes
    state: enabled
    immediate: true
- name: "Copy Config File to /etc"
  become: yes
  copy:
    src: ./build/{{ inventory_hostname }}/rsyslog.conf
    dest: /etc/rsyslog.d/server.conf
    owner: root
    group: root
    mode: 0644
- name: "Restart Rsyslog"
  become: yes
  service:
    name: tac_plus
    state: started
    enabled: yes