- name: "Open Tacacs Firewall Port"
  become: yes
  firewalld:
    port: 49/tcp
    permanent: yes
    state: enabled
    immediate: true
- name: "Copy Config File to /etc"
  become: yes
  copy:
    src: ./build/{{ inventory_hostname }}/tac_plus.conf
    dest: /etc/tac_plus.conf
    owner: root
    group: root
    mode: 0644
- name: "Restart tac_plus"
  become: yes
  service:
    name: tac_plus
    state: started
    enabled: yes