- name: "Add tac_plus repostory"
  become: yes
  when: "ansible_facts['os_family']|lower == 'redhat'"
  yum_repository:
    baseurl: "http://li.nux.ro/download/nux/misc/el6/x86_64/"
    description: "tac_plus repository"
    enabled: no
    gpgcheck: yes
    gpgkey: "http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro"
    name: "tac_plus"
- name: "Install tac_plus - Redhat"
  become: yes
  when: "ansible_facts['os_family']|lower == 'redhat'"
  yum:
    name: "tac_plus"
    state: "present"
    enablerepo: "tac_plus"