- name: "Create Config Staging Folder"
  file:
    path: "./staging/{{ inventory_hostname }}/chrony/config/"
    state: "directory"
- name: "Create Config"
  template:
    dest: "./build/{{ inventory_hostname }}/chrony.conf"
    src: "./config.j2"