- name: "Open DHCP Firewall Port"
  become: yes
  firewalld:
    immediate: yes
    permanent: yes
    service: "dhcp"
    state: "enabled"
  when: "dnsmasq.dhcp is defined"
- name: "Open DNS Firewall Port"
  become: yes
  firewalld:
    immediate: yes
    permanent: yes
    service: "dns"
    state: "enabled"
  when: "dnsmasq.dns is defined"
- name: "Copy Config File to /etc"
  become: yes
  copy:
    dest: "/etc/dnsmasq.conf"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/dnsmasq.conf"
- name: "Copy Config File to /etc"
  become: yes
  copy:
    dest: "/etc/dnsmasq.hosts"
    group: "root"
    mode: "0644"
    owner: "root"
    src: "./build/{{ inventory_hostname }}/dnsmasq.hosts"
- name: "Restart DNSMASQ"
  become: yes
  service:
    enabled: yes
    name: "dnsmasq"
    state: "restarted"
