- name: "Open DHCP Firewall Port"
  become: yes
  firewalld:
    service: dhcp
    permanent: yes
    state: enabled
    immediate: true
  when: dnsmasq.dhcp is defined
- name: "Open DNS Firewall Port"
  become: yes
  firewalld:
    service: dns
    permanent: yes
    state: enabled
    immediate: true
  when: dnsmasq.dns is defined
- name: "Copy Config File to /etc"
  become: yes
  copy:
    src: ./build/{{ inventory_hostname }}/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
- name: "Restart DNSMASQ"
  become: yes
  service: name=dnsmasq state=restarted
