- name: "Create Build Folder"
  file:
    path: "./build/{{ inventory_hostname }}/"
    state: "directory"
- name: "Assemble Config File"
  assemble:
    dest: "./build/{{ inventory_hostname }}/dnsmasq.conf"
    src: "./staging/{{ inventory_hostname }}/dnsmasq/config"
- name: "Assemble Hosts File"
  assemble:
    dest: "./build/{{ inventory_hostname }}/dnsmasq.hosts"
    src: "./staging/{{ inventory_hostname }}/dnsmasq/hosts"