- name: "Create DNS Config"
  template: src=./templates/dns-dnsmasq.j2 dest=./staging/{{ inventory_hostname }}/dnsmasq/config/{{ inventory_hostname }}_DNS.cfg
- name: "Create Hosts File"
  template: src=./templates/dns-hosts.j2 dest=./staging/{{ inventory_hostname }}/dnsmasq/hosts/{{ inventory_hostname }}_DNS.cfg