- name: "Create DNS Config"
  template:
    dest: "./staging/{{ inventory_hostname }}/dnsmasq/config/{{ inventory_hostname }}_DNS.cfg"
    src: "./templates/dns-dnsmasq.j2"
- name: "Create Hosts File"
  template:
    dest: "./staging/{{ inventory_hostname }}/dnsmasq/hosts/{{ inventory_hostname }}_DNS.cfg"
    src: "./templates/dns-hosts.j2"